# ===================================================================================================================

steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-praticals/react-app/web:latest', '.']

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-praticals/react-app/web:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image=us-central1-docker.pkg.dev/gcp-praticals/react-app/web:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'


   # We Have To Work On This Part.
   # Trigger Cloud Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'apply'
      - '--file=CloudDeployGCP/dev/pipeline.yaml'
      - '--file=CloudDeployGCP/dev/target.yaml'
      - '--region=us-central1'  # Specify the region as part of the deployment command

options:
  logging: CLOUD_LOGGING_ONLY
    

