steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-praticals/react-app-prod/web:latest', '.']

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-praticals/react-app-prod/web:latest']

  # Trigger Cloud Deploy with a Unique Release Name
  - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          DATE=$(date +%Y%m%d%H%M%S)
          RELEASE_NAME="release-${DATE}-${SHORT_SHA}"
          echo "Creating release with name: $RELEASE_NAME"
          gcloud deploy releases create $RELEASE_NAME \
            --delivery-pipeline=react-app-pipeline \
            --region=us-central1 \
            --skaffold-file=skaffold.yaml \
            --images=web=us-central1-docker.pkg.dev/gcp-praticals/react-app-prod/web:latest

substitutions:
    SHORT_SHA: "${COMMIT_SHA:0:7}"
  
options:
    logging: CLOUD_LOGGING_ONLY


