steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-praticals/react-app-prod/web:latest', '.']

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-praticals/react-app-prod/web:latest']

  # Trigger Cloud Deploy with a Unique Release Name
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release'  
      - '--delivery-pipeline=react-app-pipeline'
      - '--region=us-central1'
      - '--skaffold-file=skafflod.yaml'
      - '--images=web=us-central1-docker.pkg.dev/gcp-praticals/react-app-prod/web:latest'
      
options:
  logging: CLOUD_LOGGING_ONLY



