apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: react-app-prod
  annotations:
    run.googleapis.com/description: react-app-prod
spec:
  template:
    metadata:
      annotations:
        # run.googleapis.com/cloudsql-instances: ${DEV_CLOUDSQL_CONNECTION_STRING} # just for illustration
    spec:
      containers:
        - name: react-app-prod
          image: us-central1-docker.pkg.dev/gcp-praticals/react-app-prod/web:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi