apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: react-app-prod
  labels: 
    app: react-app-prod
description: Cloud Deploy Pipeline for React App
serialPipeline:
  stages:
    - targetId: react-app-prod
      profiles:
        - prod
      config:
        region: us-central1  
    