apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: react-app-dev
  labels: {}
requireApproval: false
run:
  location: projects/gcp-praticals/locations/us-central1

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: react-app-prod
  labels: {}
requireApproval: true
run:
  location: projects/gcp-praticals/locations/us-central1