apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: react-app-pipeline-dev
  labels: {}
requireApproval: false
run:
  location: us-central1

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: react-app-pipeline-prod
  labels: {}
requireApproval: true
run:
  location: us-central1
